-- Insert TYPES_IDENTITY_DOCUMENTS
INSERT INTO TYPES_IDENTITY_DOCUMENTS (ID_TYPE_IDENTITY_DOCUMENT, TYPE_IDENTY_DOCUMENT, ENABLED) VALUES(1, 'DNI', true);
INSERT INTO TYPES_IDENTITY_DOCUMENTS (ID_TYPE_IDENTITY_DOCUMENT, TYPE_IDENTY_DOCUMENT, ENABLED) VALUES(2, 'CE', true);
INSERT INTO TYPES_IDENTITY_DOCUMENTS (ID_TYPE_IDENTITY_DOCUMENT, TYPE_IDENTY_DOCUMENT, ENABLED) VALUES(3, 'PASAPORTE', false);

-- Insert CUSTOMERS
INSERT INTO CUSTOMERS (ID_CUSTOMER, BIRTH_DATE, CONTAC_EMAIL, CONTACT_NUMBER, ENABLED, FIRST_NAME, GENDER, LAST_NAME, NUMBER_IDENTY_DOCUMENT, PASSWORD, ID_TYPE_IDENTY_DOCUMENT) VALUES (1,'2023-03-13T22:55:54.737Z','rnoleg@hotmail.com','939914333',true,'Carlos','M','Gutierrez','23049514','123456',1);
INSERT INTO CUSTOMERS (ID_CUSTOMER,BIRTH_DATE,CONTAC_EMAIL,CONTACT_NUMBER,ENABLED,FIRST_NAME,GENDER,LAST_NAME,NUMBER_IDENTY_DOCUMENT,PASSWORD,ID_TYPE_IDENTY_DOCUMENT) VALUES (2,'1989-12-22T22:55:54.737Z','cnole@hotmail.com','939914333',true,'Rodrigo','M','Nole','43049524','123456',2);
INSERT INTO CUSTOMERS (ID_CUSTOMER,BIRTH_DATE,CONTAC_EMAIL,CONTACT_NUMBER,ENABLED,FIRST_NAME,GENDER,LAST_NAME,NUMBER_IDENTY_DOCUMENT,PASSWORD,ID_TYPE_IDENTY_DOCUMENT) VALUES (3,'1990-12-23T22:55:54.737Z','rnoleg@hotmail.com','939914333',false,'Kathy','F','Benites','23089524','123456',3);